### ISSUE TITLE
support for sharing views

### ISSUE THREAD

**Issue by FreakyBytes** [SemsProject/MOST#14]
## Trac Ticket #14
**component:** website
**owner:** somebody
**reporter:** martin
**created:** 2016-07-03 21:15:26
**milestone:** 
**type:** task
**version:** 
**keywords:** 

currently it is not possible to share what I see. when I share the link the other user will arrive at the front page but not with the stuff I've selected.

instead create shareable links. for example using

* the `#` symbol: ​http://localhost/stats-website/#tab=donut&timestart=2010-09-10&select=CellML
* the above with a `?`
* some session id or something, similar to combinearchive-web:wiki http://localhost/stats-website/share/123abc456

see also #12

**Comment by Gebbi8** [comment]
selected date range, filters and visualization are stored in url
TODO: store diff / graph tab
