### ISSUE TITLE
cannot create ticket when not logged in

### ISSUE THREAD

**Issue by FreakyBytes** [SemsProject/MOST#21]
## Trac Ticket #21
**component:** code
**owner:** somebody
**reporter:** dagmar
**created:** 2016-09-22 17:27:45
**milestone:** 
**type:** task
**version:** 
**keywords:** 

It is not allowed to create a feedback ticket without being logged in to the SEMS page, ie, externals cannot give feedback ;)

I came from http://most.sems.uni-rostock.de/
(feel free to delete this if it is not related to your report)

**Comment by Gebbi8** [comment]
solved due to the integration of the track to github
