### ISSUE TITLE
Annotations missing

### ISSUE THREAD

**Issue by FreakyBytes** [SemsProject/MOST#23]
## Trac Ticket #23
**component:** code
**owner:** somebody
**reporter:** tom
**created:** 2016-11-02 09:51:48
**milestone:** 
**type:** task
**version:** 
**keywords:** 

Sometimes no annotations are shown after the diff is computed.

**Comment by Gebbi8** [comment]
this is normal behaivour, some diffs have no annotations or graph output,
in this case the tabs are hidden now
