### ISSUE TITLE
Several windows when downloading the SBGN + SBGN file name 

### ISSUE THREAD

**Issue by vtoure** [SemsProject/MOST#31]
Several windows are opening when clicking on the download button.

Current name of the SBGN file is _sbgn-ml.sbgnml_
Should the name be changed with the model's name and versions?
Example: _BIOMD0000000022_2005-04-11_2005-07-28.sbgn_

**Comment by Gebbi8** [comment]
thanks 👍 
i dont have the bug on chrome and firefox (even edge does not open an extra window.
which system and browser do you use?

**Comment by vtoure** [comment]
Weird.. I don't have this bug today. But yesterday, I tried several times times and got multiples windows.
I am using Firefox 52.0.1 with Ubuntu 16.04.
