### ISSUE TITLE
don't compute diffs twice

### ISSUE THREAD

**Issue by FreakyBytes** [SemsProject/MOST#8]
## Trac Ticket #8
**component:** website
**owner:** somebody
**reporter:** martin
**created:** 2016-07-03 20:56:58
**milestone:** 
**type:** task
**version:** 
**keywords:** 

if i switch between diffs i don't want to call bives twice.

instead 'cache' the div and reuse it.

## comment 1
**time:** 2016-07-03 20:57:05
**author:** martin

## comment 2
**time:** 2016-07-03 20:57:05
**author:** martin

Updated **component** to **website**

**Comment by Gebbi8** [comment]
diffs are saved in session storage and retrieved if asked for
session storage is automatically deleted when the tab is closed
